Settings:
  Sounds:
    # Sound to play when a player deposits items to a team chest
    TeamChest: "BLOCK_CHEST_CLOSE"
    # Sound to play when a player deposits items to a private chest
    PrivateChest: "BLOCK_CHEST_CLOSE"

  Holograms:
    # Enable holograms
    Enabled: true
    # Hologram text
    Text:
      - "&7PUNCH TO"
      - "&7DEPOSIT"
    # Radius that the plugin will try to locate private/team chests
    Search:
      X: 8
      Y: 4
      Z: 8
    # Hologram offset
    Offsets:
      X: 0.5
      Y: 1.0
      Z: 0.5

  # Items that won't be deposited when left-clicking a container
  BlackListed-Items:
   # Weapons
   - "WOOD_SWORD"
   - "STONE_SWORD"
   - "IRON_SWORD"
   - "DIAMOND_SWORD"
   - "BOW"
   # Utility
   - "WOOD_PICKAXE"
   - "WOOD_AXE"
   - "SHEARS"

Update-Check:
  # Checks for plugin updates
  Enabled: true

Debug-Mode:
  # Enables debug mode
  Enabled: false

# DO NOT TOUCH!
Config-Version: 3