Print-SplashScreen: true

Update-Check:
  enabled: true

Settings:
  BlackListed-Items:
    - "EXAMPLE_ITEM"
#   - "WOODEN_SWORD"
  BlackListed-Containers:
    - "EXAMPLE_CONTAINER"
#   - "FURNACE"

# DO NOT TOUCH!
config-version: 1