Settings:
  # Items that won't be deposited when left-clicking a container
  BlackListed-Items:
    - "EXAMPLE_ITEM"
#   - "WOODEN_SWORD"

Update-Check:
  # Checks for plugin updates
  enabled: true

# DO NOT TOUCH!
config-version: 2